include: "https://gitlab.freedesktop.org/gstreamer/gst-ci/raw/master/gitlab/ci_template.yml"

cerbero deps fedora x86_64:
  extends: '.cerbero deps fedora x86_64'

build cerbero fedora x86_64:
  extends: '.build cerbero fedora x86_64'
  dependencies:
    - "cerbero deps fedora x86_64"
